name: Publish Package

on:
  push:
    branches:
      - master
      
jobs:
  release:
    environment: master
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Set up JDK 21
      uses: actions/setup-java@v3
      with:
        java-version: '21'
        distribution: 'temurin'
        server-id: github
        settings-path: ${{ github.workspace }}

    - name: Bump next release version
      run: |
        ./gradlew nextReleaseVersion
      
    - name: Publish to GitHub Packages
      run: ./gradlew build publish -x test
      env:
        USERNAME: ${{ github.actor }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}